### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by kgrigas** [romainberger/webpack-rtl-plugin#19]
Hey,

Is there a plan to update this plugin to support webpack 4?

**Comment by c4off** [comment]
Hi there. We're moving to webpack 4 with `mini-css-extract-plugin`. But RTL-plugin won't take into account css-chunks.

**Comment by beshanoe** [comment]
@c4off I've encountered the same issue, didn't solve it yet
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/217
We need to elaborate on possible solution because it seems tricky.
For example, there could be some globally defined function which accepts file path and list of css chunks  with paths as arguments and returns the new path. Because we can't just alter the suffix(like .rtl.css) since there can also be a unique hash

**Comment by romainberger** [comment]
Hi, I've just published version 2.0.0 that should be compatible with webpack 4. Please let me know if you have any issues. Thanks
